#!/bin/sh
#
# Shell script to convert and code written to the alpha API (when the module
# was called Getopt::XML) to the release API
#

perl -p -i -e 's/Getopt::XML/XML::Simple/g; s/XMLToOpt/XMLin/g; s/OptToXML/XMLout/g;' $*
